### ISSUE TITLE
Error generating token

### ISSUE THREAD

**Issue by karlnewell** [grnet/flowspy#10]
I receive "An error has occured..." when generating a token on the My Profile page.  

If I browse to /profile/token/ the following debug info is displayed.

AttributeError at /profile/token/
type object 'Token' has no attribute 'DoesNotExist'
Request Method: GET
Request URL:    http://nsnocdev2.internet2.edu:8080/profile/token/
Django Version: 1.4.22
Exception Type: AttributeError
Exception Value:  
type object 'Token' has no attribute 'DoesNotExist'
Exception Location: /srv/flowspy/accounts/views.py in generate_token, line 40
Python Executable:  /usr/bin/python
Python Version: 2.7.3
Python Path:  
['/srv/flowspy/flowspy',
 '/srv/flowspy',
 '/usr/bin',
 '/usr/local/lib/python2.7/dist-packages/ncclient-0.5.2-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/lxml-3.6.4-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/flowspy_graphs-0.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/requests-2.11.1-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/pymodules/python2.7']
Server time:    Fri, 28 Oct 2016 13:46:47 -0700

Traceback - http://dpaste.com/0CW599B

**Comment by safts** [comment]
Please excuse my late reply. I am not sure what goes wrong with your setup, I tested it right now in our development / production instances and it seems to work fine. I cannot see the traceback, it must have been deleted. Can you resend it?

**Comment by karlnewell** [comment]
Environment:

Request Method: GET
Request URL: http://nsnocdev2.internet2.edu:8080/profile/token/

Django Version: 1.4.22
Python Version: 2.7.3
Installed Applications:
('longerusername',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.flatpages',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'flowspec',
 'poller',
 'south',
 'django.contrib.admin',
 'djcelery',
 'peers',
 'registration',
 'accounts',
 'tinymce',
 'widget_tweaks')
Installed Middleware:
('django.middleware.cache.UpdateCacheMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.cache.FetchFromCacheMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware')

Traceback:
File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
1.                         response = callback(request, _callback_args, *_callback_kwargs)
   File "/srv/flowspy/accounts/views.py" in generate_token
2.     except Token.DoesNotExist:

Exception Type: AttributeError at /profile/token/
Exception Value: type object 'Token' has no attribute 'DoesNotExist'

**Comment by safts** [comment]
You need to have `rest_framework`, `rest_framework.authtoken` in your `INSTALLED_APPS`. Add those, run `./manage.py migrate` and the issue should be fixed.

**Comment by karlnewell** [comment]
Thanks, got it working. I had to manually add `rest_framework` and `rest_framework.authtoken` into `INSTALLED_APPS` in `settings.py`.  Is there a reason this is not the default in the repo?  Would you like me to submit a pull request to update `settings.py.dist`?

**Comment by safts** [comment]
I guess using the REST API at some point was considered optional but this is no longer the case. Sure, you can go ahead. Thanks.
