### ISSUE TITLE
Debian Install problems

### ISSUE THREAD

**Issue by sonicepk** [grnet/flowspy#3]
Hi GRnet team,

I am trying to do a clean Debian wheezy install of Flowspy.  I have followed the instructions from here:
http://flowspy.readthedocs.io/en/latest/installation/debian_wheezy/#installing-from-scratch

But I think I have hit a python package dependency issues. Possibly with six and the Django rest framework. The installed packages are listed here 
[fod.txt](https://github.com/grnet/flowspy/files/289830/fod.txt)
  and below is the error message ("ImportError: No module named response") I am getting. 

Any help/suggestions would be greatly appreciated.

Regards
Eoin

When I go the the webpage I get the following error:
Internal Server Error
Traceback:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/async.py", line 39, in handle
    self.handle_request(req, client, addr)
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 86, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/async.py", line 69, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 241, in **call**
    response = self.get_response(request)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 177, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 222, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/usr/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/srv/flowspy/flowspy/urls.py", line 7, in 
    from rest_framework import routers
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/routers.py", line 25, in 
    from rest_framework import views
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 9, in 
    from django.http.response import HttpResponseBase
ImportError: No module named response

**Comment by safts** [comment]
Hello,

The version of `djangorestframework` you have installed is not compatible. Try installing the official debian package, it is now available.

**Comment by bilbolodz** [comment]
Could you please provide name of the package for wheezy?

**Comment by safts** [comment]
The package name is `python-djangorestframework`

**Comment by bilbolodz** [comment]
Hmmmmmm

root@fod:~# cat /etc/debian_version 
7.10
root@fod:~# apt-cache search python-djangorestframework

[null]

root@fod:~# apt-cache search python-django
python-celery - async task/job queue based on message passing
python-celery-doc - async task/job queue based on message passing (Documentation)
python-django-dajaxice - agnostic and easy to use AJAX library for django
python-django-adminaudit - improves the logging capabilities of Django's admin
python-django-app-plugins - plugin system for django
python-django-auth-ldap - Django LDAP authentication backend
python-django-auth-ldap-doc - Django LDAP authentication backend (documentation)
python-django-authority - more powerful permission system for Django
python-django-celery - Celery integration for Django
python-django-celery-doc - Celery integration for Django (Documentation)
python-django-classy-tags - Class based template tags for Django projects
python-django-countries - provides a country field for Django models
python-django-dajax - easy to use ajax library for django
python-django-evolution - Implementation of schema evolution for the Django web framework
python-django-extra-views - Extra class-based views for Django
python-django-floppyforms - better control of form rendering in Django
python-django-genshi - Django integration for Genshi
python-django-markupfield - custom Django field for easy use of markup in text fields
python-django-nose - Django test runner that uses python-nose
python-django-notification - user notification management for Django
python-django-auth-openid - provides optional OpenID integration for Django
python-django-pagination - utilities for creating pagination tools for Django
python-django-picklefield - Pickled object field for Django
python-django-reversion - Provides comprehensive version control facilities for Django
python-django-sekizai - template blocks for Django projects
python-django-threaded-multihost - allows to serve multiple sites from one django installation
python-django-horizon - Django module providing web interaction with OpenStack
mumble-django - Mumble-Server web interface
python-django-mumble - Mumble-Server config application for Django
python-django - High-level Python web development framework
python-django-doc - High-level Python web development framework (documentation)
python-django-contact-form - extensible contact-form application for Django
python-django-debug-toolbar - Embedded debugging toolbar for Django projects
python-django-djapian - Search API for Django using Xapian
python-django-extdirect - Ext.Direct serverside implementation for Django
python-django-feincms - Django-based Page CMS and CMS building toolkit
python-django-feincms-doc - Django-based Page CMS and CMS building toolkit - documentation
python-django-formfieldset - fieldset rendering mixin for Django-based forms
python-django-lint - Static analysis tool for Django projects and applications
python-django-localeurl - Django application allows the language be set in the URL
python-django-mptt - Modified Preorder Tree Traversal Django application
python-django-registration - User-registration application for Django
python-django-rosetta - Eases the translation process of your Django projects
python-django-shorturls - Short URL handler for Django applications
python-django-social-auth - Django social authentication made simple
python-django-south - Intelligent schema migrations for django apps
python-django-tagging - Generic tagging application for Django projects
python-django-threadedcomments - simple yet flexible threaded commenting system for Django
python-django-tinymce - replacement text widget for Django web framework
python-django-treebeard - Efficient implementations of tree data structures for Django
python-django-treebeard-doc - Efficient implementations of tree data structures for Django (documentation)
python-django-voting - generic voting application for Django
python-django-websocket - Websocket support for django
python-django-uwsgi-admin - Django application for administering uWSGI server

**Comment by safts** [comment]
My bad. Seems that this package was created by our system administrators. When you install this package from pip it installs the latest version which is not compatible. If you install v2.4.8 you should be fine ( `pip install djangorestframework==2.4.8`)

**Comment by bilbolodz** [comment]
OK, installed djangorestframework==2.4.8

Now next error:

Internal Server Error
Traceback:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/async.py", line 39, in handle
    self.handle_request(req, client, addr)
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 86, in handle_request
    super(GeventWorker, self).handle_request(_args)
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/async.py", line 69, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 241, in **call**
    response = self.get_response(request)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 177, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 226, in handle_uncaught_exception
    return callback(request, *_param_dict)
  File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/defaults.py", line 32, in server_error
    t = loader.get_template(template_name) # You need to create a 500.html template.
  File "/usr/lib/python2.7/dist-packages/django/template/loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "/usr/lib/python2.7/dist-packages/django/template/loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: 500.html

**Comment by safts** [comment]
Seems like your `settings.py` is not configured correctly. 

You can try putting the absolute path to your `templates` in your `TEMPLATES_DIRS` tuple. E.g. in our production environment we have `/srv/flowspy/templates/` .

**Comment by bilbolodz** [comment]
Better, next error (nicer HTML with image and text):

---

The service is currently unavailiable - Internal error
Our firestrators have been notified with this problem. We apologize for the inconvenience
In the meantime, a team of brave firebuilders is on the spot, placing bricks on the firewall
They are about to light the fire again

---

Where to find more details about error?

**Comment by safts** [comment]
This is the custom HTTP500 error page the service displays. To find more you can set `DEBUG = False` in `settings.py`. This will show you the page django provides which contains information about the error.

**Comment by sonicepk** [comment]
Thanks Sergafts. Changing to 2.4.8 worked.
I got the warnings below but everything looks ok at the moment.

Regards
Eoin

root@fod:# pip install djangorestframework==2.4.8
Downloading/unpacking djangorestframework==2.4.8
  Downloading djangorestframework-2.4.8.tar.gz (175Kb): 175Kb downloaded
  Running setup.py egg_info for package djangorestframework

```
warning: no previously-included files matching '__pycache__' found under direc                                                                        tory '*'
warning: no previously-included files matching '*.py[co]' found under director                                                                        y '*'
```

Installing collected packages: djangorestframework
  Running setup.py install for djangorestframework

```
warning: no previously-included files matching '__pycache__' found under direc                                                                        tory '*'
warning: no previously-included files matching '*.py[co]' found under director                                                                        y '*'
```

Successfully installed djangorestframework
Cleaning up...
