### ISSUE TITLE
Celerybeat unable to connect

### ISSUE THREAD

**Issue by sonicepk** [grnet/flowspy#4]
Hi GRNET team,

I have a problem with Celery and I am hoping you might be able to assist me. I followed the Debian install instructions but Celery is not working as I expected. 
When I restart the server, Celerybeat does not start properly. The error messages are:
From:/var/log/celerybeat.log

[2016-06-02 11:34:12,473: WARNING/MainProcess] celerybeat v2.5.3 is starting.
[2016-06-02 11:34:13,365: WARNING/MainProcess] __    -    ... __   -        _
Configuration ->
    . broker -> amqp://guest@localhost:5672//
    . loader -> celery.loaders.default.Loader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> /var/log/celerybeat.log@INFO
    . maxinterval -> 5.00 minutes (300s)
[2016-06-02 11:34:13,365: INFO/MainProcess] Celerybeat: Starting...
[2016-06-02 11:34:13,679: ERROR/MainProcess] Celerybeat: Connection error: [Errno 111] Connection refused. Trying again in 2.0 seconds...

I don't have a "celeryconfig" file anywhere but I understand that the celery/beanstalk interaction is controlled via django and in my settings.py I have:
BROKER_HOST = "localhost"
BROKER_PORT = 11300
POLLS_TUBE = 'polls'
BROKER_URL = "beanstalk://localhost:11300//"
BROKER_VHOST = "/"
CELERY_CONCURRENCY = 1

If I run ./manage.py celeryd --loglevel=debug, celery runs and pushes the same config repeatedly to my Juniper router. 

Any help/ideas would be great.

Thanks
Eoin
[celeryd.txt](https://github.com/grnet/flowspy/files/295445/celeryd.txt)
[celery_w1.txt](https://github.com/grnet/flowspy/files/295451/celery_w1.txt)

**Comment by sonicepk** [comment]
IThe only way I can get Celery to behave is if I run it from django. root@fod:/srv/flowspy# ./manage.py celeryd&. Then everything works fine. If I try and use /etc/init.d/celeryd the netconf config is loaded repeatedly.....

**Comment by bilbolodz** [comment]
I've the same behavior  (continuous loop loading config to device). Unfortunately  " ./manage.py celeryd" trick is NOT working for me. The same situation using /etc/init.d script and manage.py.

**Comment by sonicepk** [comment]
Sorry I should also have said that I switched to 1.1.1 rather than 1.2. 

I am using flowspy --- netconf (Juniper MX) ---(ibgp)---Cisco IOSXR

**Comment by bilbolodz** [comment]
You mean version: 1.1.2 (not 1.2)?

**Comment by sonicepk** [comment]
I used this version. 
https://github.com/grnet/flowspy/releases/tag/v1.1.1

**Comment by safts** [comment]
@sonicepk 

I am a bit confused. Quoting:

> If I run ./manage.py celeryd --loglevel=debug, celery runs and pushes the same config repeatedly to my Juniper router.

So, here I understand that running from Django pushes the same configuration multiple times. But:

> The only way I can get Celery to behave is if I run it from django. root@fod:/srv/flowspy# ./manage.py celeryd&

So, does running celery from django work or not? Does it keep pushing the same configuration?

**Comment by safts** [comment]
@sonicepk 
As far as celerybeat is concerned, I see that it does not know where to connect to. Please see
https://ask.github.io/celery/cookbook/daemonizing.html#init-script-celerybeat

**Comment by sonicepk** [comment]
@sergafts 
If I run ./manage.py celeryd  with version 1.2 it repeatedly pushes the same config to the netconf device.
If I run ./manage.py celeryd with version 1.1.1 it works as expected. Pushing the config once.

**Comment by sonicepk** [comment]
@sergafts 
Adding the following to my /etc/defaults/celeryd allows cerlerybeat to run ok when started from the init script. 
CELERYBEAT_CHDIR="/srv/flowspy"
CELERYBEAT="/srv/flowspy/manage.py celerybeat"
CELERYBEAT_OPTS="--schedule=/var/run/celerybeat-schedule"

**Comment by safts** [comment]
@sonicepk 
Great. As for the 1.2 version problem, I am working on it but it will probably take a while. I will let you know when I have something new.

**Comment by safts** [comment]
@bilbolodz 
Have you tried using v1.1.1 as @sonicepk suggested? Does this work for you too?

**Comment by bilbolodz** [comment]
I will try but my friend has properly working version 1.2! Strange.....

**Comment by bilbolodz** [comment]
I've installed version 1.2 from https://github.com/grnet/flowspy and it solved my problem with celeryd commit looping.

**Comment by safts** [comment]
@bilbolodz Did you follow a different procedure than the one described in the docs? If so, could you please provide some further information so that I can update them?

**Comment by bilbolodz** [comment]
I've followed instruction from these web page https://flowspy.readthedocs.io/en/latest/installation/debian_wheezy/ and then get version 1.2 from https://github.com/grnet/flowspy and replaced flowspy files.

**Comment by sonicepk** [comment]
Following a reboot I found celeryd and celerybeat would not start. The reason why is that celeryd and celerybeat were starting before mysql. 
Adding to celeryd init script
"# Required-Start:    +mysql "
insserv celeryd
Adding to celerybeat init script
"# Required-Start:     $network $local_fs $remote_fs +mysql"
insserv celerybeat

Changes the boot sequence to make celerybeat and celeryd start after mysql which resolves the issue.

Thanks for all the help.
