### ISSUE TITLE
ENTITLEMENT 

### ISSUE THREAD

**Issue by Edugate** [grnet/flowspy#5]
I am releasing an edupersonentitlemt value urn:mace:heanet.ie:... and have set SHIB_AUTH_ENTITLEMENT in views.py to 'urn:mace:heanet' but I still get the "Your idP should release an appropriate HTTP_SHIB_EP_ENTITLEMENT attribute towards this service" error.

Is there any way to debug what's causing this?

Also, it's not clear how peers and orgs are related, particularly with regard to shib auth.

**Comment by jkakavas** [comment]
Hi, 
The value of the eduPersonEntitlement is checked with a string comparison for the whole string, not just the URN prefix ( https://github.com/grnet/flowspy/blob/085dec60937c022786081f2c059f4cb281a57dc7/flowspec/views.py#L525 ) . 

As such, if you are releasing a value of 'urn:mace:heanet.ie:ioannis' for example, you should set
SHIB_AUTH_ENTITLEMENT = 'urn:mace:heanet.ie:ioannis'
in your settings.py

**Comment by safts** [comment]
Let me describe the login process, I think it will help clear things out.

The first time a user tries to log in using shibboleth he is redirected to his idP's service for authentication.

If authentication is successful, he is redirected back to our service to select his Institution (Peer). When he does, the site administrators (the addresses specified in `settings.NOTIFY_ADMIN_MAILS`) receive an email containing the user's information, the Institution (Peer) he selected during registration and a link to activate the user's account.

When doing so, an admin can change the User's Institution to ensure that he is assigned to the correct Institution. 

User's organization does not derive from Shibboleth. It is defined statically and administrators can later verify or change it.

**Comment by safts** [comment]
Closing the issue.
